### PR TITLE
Fix issue#4, "flake8 not found" OS X #4

### PR DESCRIPTION
**Pull request by nspforever**
flake8 extension always complain about "flake8 not found", this is due to flake8 by default is not in the system path of OS X, so change this setting default to false will get rid of the pain of Mac OS X user. And pep8 extension set the pep8InSystemPath = false too.

### CODE REVIEW

**Comment by nspforever** [comment]
This fix should get the issue#4 fixed.

**Comment by nspforever** [comment]
Closed the pull request by mistake, please take this change into consideration, thanks!

**Comment by marcoceppi** [comment]
This preference can be overridden from the configuration pane of the plugin. Changing the default just makes it work better for one group of people and not another

**Comment by nspforever** [comment]
Agree, but seems this change will make both OS X and Ubuntu user happy.

**Pull request closed without merging**
